// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public static partial class CreateRoom {

  #region Extension registration
  public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
  }
  #endregion
  #region Static variables
  internal static pbd::MessageDescriptor internal__static_sendCreateRoom__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::sendCreateRoom, global::sendCreateRoom.Builder> internal__static_sendCreateRoom__FieldAccessorTable;
  internal static pbd::MessageDescriptor internal__static_returnCreateRoom__Descriptor;
  internal static pb::FieldAccess.FieldAccessorTable<global::returnCreateRoom, global::returnCreateRoom.Builder> internal__static_returnCreateRoom__FieldAccessorTable;
  #endregion
  #region Descriptor
  public static pbd::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbd::FileDescriptor descriptor;
  
  static CreateRoom() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChBDcmVhdGVSb29tLnByb3RvIqUBCg5zZW5kQ3JlYXRlUm9vbRIQCgh1c2Vy", 
          "bmFtZRgBIAEoCRIOCgZpc193Z2oYAiACKAUSEgoKaXNfeGlucWlqaRgDIAIo", 
          "BRIVCg1pc19zaGFuZ3hpYWppGAQgAigFEhAKCGlzX2JlbmppGAUgAigFEhMK", 
          "C2lzX3lpa291c2FuGAYgAigFEhAKCHJvb21fcGVvGAcgASgJEg0KBWNvdW50", 
          "GAggAigFIjQKEHJldHVybkNyZWF0ZVJvb20SDgoGcm9vbUlEGAEgAigFEhAK", 
        "CHVzZXJpbmZvGAIgAigJ"));
    pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
      descriptor = root;
      internal__static_sendCreateRoom__Descriptor = Descriptor.MessageTypes[0];
      internal__static_sendCreateRoom__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::sendCreateRoom, global::sendCreateRoom.Builder>(internal__static_sendCreateRoom__Descriptor,
              new string[] { "Username", "IsWgj", "IsXinqiji", "IsShangxiaji", "IsBenji", "IsYikousan", "RoomPeo", "Count", });
      internal__static_returnCreateRoom__Descriptor = Descriptor.MessageTypes[1];
      internal__static_returnCreateRoom__FieldAccessorTable = 
          new pb::FieldAccess.FieldAccessorTable<global::returnCreateRoom, global::returnCreateRoom.Builder>(internal__static_returnCreateRoom__Descriptor,
              new string[] { "RoomID", "Userinfo", });
      return null;
    };
    pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
        new pbd::FileDescriptor[] {
        }, assigner);
  }
  #endregion
  
}
#region Messages
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class sendCreateRoom : pb::GeneratedMessage<sendCreateRoom, sendCreateRoom.Builder> {
  private sendCreateRoom() { }
  private static readonly sendCreateRoom defaultInstance = new sendCreateRoom().MakeReadOnly();
  private static readonly string[] _sendCreateRoomFieldNames = new string[] { "count", "is_benji", "is_shangxiaji", "is_wgj", "is_xinqiji", "is_yikousan", "room_peo", "username" };
  private static readonly uint[] _sendCreateRoomFieldTags = new uint[] { 64, 40, 32, 16, 24, 48, 58, 10 };
  public static sendCreateRoom DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override sendCreateRoom DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override sendCreateRoom ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::CreateRoom.internal__static_sendCreateRoom__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<sendCreateRoom, sendCreateRoom.Builder> InternalFieldAccessors {
    get { return global::CreateRoom.internal__static_sendCreateRoom__FieldAccessorTable; }
  }
  
  public const int UsernameFieldNumber = 1;
  private bool hasUsername;
  private string username_ = "";
  public bool HasUsername {
    get { return hasUsername; }
  }
  public string Username {
    get { return username_; }
  }
  
  public const int IsWgjFieldNumber = 2;
  private bool hasIsWgj;
  private int isWgj_;
  public bool HasIsWgj {
    get { return hasIsWgj; }
  }
  public int IsWgj {
    get { return isWgj_; }
  }
  
  public const int IsXinqijiFieldNumber = 3;
  private bool hasIsXinqiji;
  private int isXinqiji_;
  public bool HasIsXinqiji {
    get { return hasIsXinqiji; }
  }
  public int IsXinqiji {
    get { return isXinqiji_; }
  }
  
  public const int IsShangxiajiFieldNumber = 4;
  private bool hasIsShangxiaji;
  private int isShangxiaji_;
  public bool HasIsShangxiaji {
    get { return hasIsShangxiaji; }
  }
  public int IsShangxiaji {
    get { return isShangxiaji_; }
  }
  
  public const int IsBenjiFieldNumber = 5;
  private bool hasIsBenji;
  private int isBenji_;
  public bool HasIsBenji {
    get { return hasIsBenji; }
  }
  public int IsBenji {
    get { return isBenji_; }
  }
  
  public const int IsYikousanFieldNumber = 6;
  private bool hasIsYikousan;
  private int isYikousan_;
  public bool HasIsYikousan {
    get { return hasIsYikousan; }
  }
  public int IsYikousan {
    get { return isYikousan_; }
  }
  
  public const int RoomPeoFieldNumber = 7;
  private bool hasRoomPeo;
  private string roomPeo_ = "";
  public bool HasRoomPeo {
    get { return hasRoomPeo; }
  }
  public string RoomPeo {
    get { return roomPeo_; }
  }
  
  public const int CountFieldNumber = 8;
  private bool hasCount;
  private int count_;
  public bool HasCount {
    get { return hasCount; }
  }
  public int Count {
    get { return count_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasIsWgj) return false;
      if (!hasIsXinqiji) return false;
      if (!hasIsShangxiaji) return false;
      if (!hasIsBenji) return false;
      if (!hasIsYikousan) return false;
      if (!hasCount) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _sendCreateRoomFieldNames;
    if (hasUsername) {
      output.WriteString(1, field_names[7], Username);
    }
    if (hasIsWgj) {
      output.WriteInt32(2, field_names[3], IsWgj);
    }
    if (hasIsXinqiji) {
      output.WriteInt32(3, field_names[4], IsXinqiji);
    }
    if (hasIsShangxiaji) {
      output.WriteInt32(4, field_names[2], IsShangxiaji);
    }
    if (hasIsBenji) {
      output.WriteInt32(5, field_names[1], IsBenji);
    }
    if (hasIsYikousan) {
      output.WriteInt32(6, field_names[5], IsYikousan);
    }
    if (hasRoomPeo) {
      output.WriteString(7, field_names[6], RoomPeo);
    }
    if (hasCount) {
      output.WriteInt32(8, field_names[0], Count);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasUsername) {
      size += pb::CodedOutputStream.ComputeStringSize(1, Username);
    }
    if (hasIsWgj) {
      size += pb::CodedOutputStream.ComputeInt32Size(2, IsWgj);
    }
    if (hasIsXinqiji) {
      size += pb::CodedOutputStream.ComputeInt32Size(3, IsXinqiji);
    }
    if (hasIsShangxiaji) {
      size += pb::CodedOutputStream.ComputeInt32Size(4, IsShangxiaji);
    }
    if (hasIsBenji) {
      size += pb::CodedOutputStream.ComputeInt32Size(5, IsBenji);
    }
    if (hasIsYikousan) {
      size += pb::CodedOutputStream.ComputeInt32Size(6, IsYikousan);
    }
    if (hasRoomPeo) {
      size += pb::CodedOutputStream.ComputeStringSize(7, RoomPeo);
    }
    if (hasCount) {
      size += pb::CodedOutputStream.ComputeInt32Size(8, Count);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static sendCreateRoom ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static sendCreateRoom ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static sendCreateRoom ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static sendCreateRoom ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private sendCreateRoom MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(sendCreateRoom prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<sendCreateRoom, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(sendCreateRoom cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private sendCreateRoom result;
    
    private sendCreateRoom PrepareBuilder() {
      if (resultIsReadOnly) {
        sendCreateRoom original = result;
        result = new sendCreateRoom();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override sendCreateRoom MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::sendCreateRoom.Descriptor; }
    }
    
    public override sendCreateRoom DefaultInstanceForType {
      get { return global::sendCreateRoom.DefaultInstance; }
    }
    
    public override sendCreateRoom BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is sendCreateRoom) {
        return MergeFrom((sendCreateRoom) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(sendCreateRoom other) {
      if (other == global::sendCreateRoom.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasUsername) {
        Username = other.Username;
      }
      if (other.HasIsWgj) {
        IsWgj = other.IsWgj;
      }
      if (other.HasIsXinqiji) {
        IsXinqiji = other.IsXinqiji;
      }
      if (other.HasIsShangxiaji) {
        IsShangxiaji = other.IsShangxiaji;
      }
      if (other.HasIsBenji) {
        IsBenji = other.IsBenji;
      }
      if (other.HasIsYikousan) {
        IsYikousan = other.IsYikousan;
      }
      if (other.HasRoomPeo) {
        RoomPeo = other.RoomPeo;
      }
      if (other.HasCount) {
        Count = other.Count;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_sendCreateRoomFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _sendCreateRoomFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 10: {
            result.hasUsername = input.ReadString(ref result.username_);
            break;
          }
          case 16: {
            result.hasIsWgj = input.ReadInt32(ref result.isWgj_);
            break;
          }
          case 24: {
            result.hasIsXinqiji = input.ReadInt32(ref result.isXinqiji_);
            break;
          }
          case 32: {
            result.hasIsShangxiaji = input.ReadInt32(ref result.isShangxiaji_);
            break;
          }
          case 40: {
            result.hasIsBenji = input.ReadInt32(ref result.isBenji_);
            break;
          }
          case 48: {
            result.hasIsYikousan = input.ReadInt32(ref result.isYikousan_);
            break;
          }
          case 58: {
            result.hasRoomPeo = input.ReadString(ref result.roomPeo_);
            break;
          }
          case 64: {
            result.hasCount = input.ReadInt32(ref result.count_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasUsername {
      get { return result.hasUsername; }
    }
    public string Username {
      get { return result.Username; }
      set { SetUsername(value); }
    }
    public Builder SetUsername(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasUsername = true;
      result.username_ = value;
      return this;
    }
    public Builder ClearUsername() {
      PrepareBuilder();
      result.hasUsername = false;
      result.username_ = "";
      return this;
    }
    
    public bool HasIsWgj {
      get { return result.hasIsWgj; }
    }
    public int IsWgj {
      get { return result.IsWgj; }
      set { SetIsWgj(value); }
    }
    public Builder SetIsWgj(int value) {
      PrepareBuilder();
      result.hasIsWgj = true;
      result.isWgj_ = value;
      return this;
    }
    public Builder ClearIsWgj() {
      PrepareBuilder();
      result.hasIsWgj = false;
      result.isWgj_ = 0;
      return this;
    }
    
    public bool HasIsXinqiji {
      get { return result.hasIsXinqiji; }
    }
    public int IsXinqiji {
      get { return result.IsXinqiji; }
      set { SetIsXinqiji(value); }
    }
    public Builder SetIsXinqiji(int value) {
      PrepareBuilder();
      result.hasIsXinqiji = true;
      result.isXinqiji_ = value;
      return this;
    }
    public Builder ClearIsXinqiji() {
      PrepareBuilder();
      result.hasIsXinqiji = false;
      result.isXinqiji_ = 0;
      return this;
    }
    
    public bool HasIsShangxiaji {
      get { return result.hasIsShangxiaji; }
    }
    public int IsShangxiaji {
      get { return result.IsShangxiaji; }
      set { SetIsShangxiaji(value); }
    }
    public Builder SetIsShangxiaji(int value) {
      PrepareBuilder();
      result.hasIsShangxiaji = true;
      result.isShangxiaji_ = value;
      return this;
    }
    public Builder ClearIsShangxiaji() {
      PrepareBuilder();
      result.hasIsShangxiaji = false;
      result.isShangxiaji_ = 0;
      return this;
    }
    
    public bool HasIsBenji {
      get { return result.hasIsBenji; }
    }
    public int IsBenji {
      get { return result.IsBenji; }
      set { SetIsBenji(value); }
    }
    public Builder SetIsBenji(int value) {
      PrepareBuilder();
      result.hasIsBenji = true;
      result.isBenji_ = value;
      return this;
    }
    public Builder ClearIsBenji() {
      PrepareBuilder();
      result.hasIsBenji = false;
      result.isBenji_ = 0;
      return this;
    }
    
    public bool HasIsYikousan {
      get { return result.hasIsYikousan; }
    }
    public int IsYikousan {
      get { return result.IsYikousan; }
      set { SetIsYikousan(value); }
    }
    public Builder SetIsYikousan(int value) {
      PrepareBuilder();
      result.hasIsYikousan = true;
      result.isYikousan_ = value;
      return this;
    }
    public Builder ClearIsYikousan() {
      PrepareBuilder();
      result.hasIsYikousan = false;
      result.isYikousan_ = 0;
      return this;
    }
    
    public bool HasRoomPeo {
      get { return result.hasRoomPeo; }
    }
    public string RoomPeo {
      get { return result.RoomPeo; }
      set { SetRoomPeo(value); }
    }
    public Builder SetRoomPeo(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasRoomPeo = true;
      result.roomPeo_ = value;
      return this;
    }
    public Builder ClearRoomPeo() {
      PrepareBuilder();
      result.hasRoomPeo = false;
      result.roomPeo_ = "";
      return this;
    }
    
    public bool HasCount {
      get { return result.hasCount; }
    }
    public int Count {
      get { return result.Count; }
      set { SetCount(value); }
    }
    public Builder SetCount(int value) {
      PrepareBuilder();
      result.hasCount = true;
      result.count_ = value;
      return this;
    }
    public Builder ClearCount() {
      PrepareBuilder();
      result.hasCount = false;
      result.count_ = 0;
      return this;
    }
  }
  static sendCreateRoom() {
    object.ReferenceEquals(global::CreateRoom.Descriptor, null);
  }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
public sealed partial class returnCreateRoom : pb::GeneratedMessage<returnCreateRoom, returnCreateRoom.Builder> {
  private returnCreateRoom() { }
  private static readonly returnCreateRoom defaultInstance = new returnCreateRoom().MakeReadOnly();
  private static readonly string[] _returnCreateRoomFieldNames = new string[] { "roomID", "userinfo" };
  private static readonly uint[] _returnCreateRoomFieldTags = new uint[] { 8, 18 };
  public static returnCreateRoom DefaultInstance {
    get { return defaultInstance; }
  }
  
  public override returnCreateRoom DefaultInstanceForType {
    get { return DefaultInstance; }
  }
  
  protected override returnCreateRoom ThisMessage {
    get { return this; }
  }
  
  public static pbd::MessageDescriptor Descriptor {
    get { return global::CreateRoom.internal__static_returnCreateRoom__Descriptor; }
  }
  
  protected override pb::FieldAccess.FieldAccessorTable<returnCreateRoom, returnCreateRoom.Builder> InternalFieldAccessors {
    get { return global::CreateRoom.internal__static_returnCreateRoom__FieldAccessorTable; }
  }
  
  public const int RoomIDFieldNumber = 1;
  private bool hasRoomID;
  private int roomID_;
  public bool HasRoomID {
    get { return hasRoomID; }
  }
  public int RoomID {
    get { return roomID_; }
  }
  
  public const int UserinfoFieldNumber = 2;
  private bool hasUserinfo;
  private string userinfo_ = "";
  public bool HasUserinfo {
    get { return hasUserinfo; }
  }
  public string Userinfo {
    get { return userinfo_; }
  }
  
  public override bool IsInitialized {
    get {
      if (!hasRoomID) return false;
      if (!hasUserinfo) return false;
      return true;
    }
  }
  
  public override void WriteTo(pb::ICodedOutputStream output) {
    CalcSerializedSize();
    string[] field_names = _returnCreateRoomFieldNames;
    if (hasRoomID) {
      output.WriteInt32(1, field_names[0], RoomID);
    }
    if (hasUserinfo) {
      output.WriteString(2, field_names[1], Userinfo);
    }
    UnknownFields.WriteTo(output);
  }
  
  private int memoizedSerializedSize = -1;
  public override int SerializedSize {
    get {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
      return CalcSerializedSize();
    }
  }
  
  private int CalcSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;
    
    size = 0;
    if (hasRoomID) {
      size += pb::CodedOutputStream.ComputeInt32Size(1, RoomID);
    }
    if (hasUserinfo) {
      size += pb::CodedOutputStream.ComputeStringSize(2, Userinfo);
    }
    size += UnknownFields.SerializedSize;
    memoizedSerializedSize = size;
    return size;
  }
  public static returnCreateRoom ParseFrom(pb::ByteString data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(byte[] data) {
    return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(global::System.IO.Stream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  public static returnCreateRoom ParseDelimitedFrom(global::System.IO.Stream input) {
    return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
  }
  public static returnCreateRoom ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
    return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(pb::ICodedInputStream input) {
    return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
  }
  public static returnCreateRoom ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
    return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
  }
  private returnCreateRoom MakeReadOnly() {
    return this;
  }
  
  public static Builder CreateBuilder() { return new Builder(); }
  public override Builder ToBuilder() { return CreateBuilder(this); }
  public override Builder CreateBuilderForType() { return new Builder(); }
  public static Builder CreateBuilder(returnCreateRoom prototype) {
    return new Builder(prototype);
  }
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public sealed partial class Builder : pb::GeneratedBuilder<returnCreateRoom, Builder> {
    protected override Builder ThisBuilder {
      get { return this; }
    }
    public Builder() {
      result = DefaultInstance;
      resultIsReadOnly = true;
    }
    internal Builder(returnCreateRoom cloneFrom) {
      result = cloneFrom;
      resultIsReadOnly = true;
    }
    
    private bool resultIsReadOnly;
    private returnCreateRoom result;
    
    private returnCreateRoom PrepareBuilder() {
      if (resultIsReadOnly) {
        returnCreateRoom original = result;
        result = new returnCreateRoom();
        resultIsReadOnly = false;
        MergeFrom(original);
      }
      return result;
    }
    
    public override bool IsInitialized {
      get { return result.IsInitialized; }
    }
    
    protected override returnCreateRoom MessageBeingBuilt {
      get { return PrepareBuilder(); }
    }
    
    public override Builder Clear() {
      result = DefaultInstance;
      resultIsReadOnly = true;
      return this;
    }
    
    public override Builder Clone() {
      if (resultIsReadOnly) {
        return new Builder(result);
      } else {
        return new Builder().MergeFrom(result);
      }
    }
    
    public override pbd::MessageDescriptor DescriptorForType {
      get { return global::returnCreateRoom.Descriptor; }
    }
    
    public override returnCreateRoom DefaultInstanceForType {
      get { return global::returnCreateRoom.DefaultInstance; }
    }
    
    public override returnCreateRoom BuildPartial() {
      if (resultIsReadOnly) {
        return result;
      }
      resultIsReadOnly = true;
      return result.MakeReadOnly();
    }
    
    public override Builder MergeFrom(pb::IMessage other) {
      if (other is returnCreateRoom) {
        return MergeFrom((returnCreateRoom) other);
      } else {
        base.MergeFrom(other);
        return this;
      }
    }
    
    public override Builder MergeFrom(returnCreateRoom other) {
      if (other == global::returnCreateRoom.DefaultInstance) return this;
      PrepareBuilder();
      if (other.HasRoomID) {
        RoomID = other.RoomID;
      }
      if (other.HasUserinfo) {
        Userinfo = other.Userinfo;
      }
      this.MergeUnknownFields(other.UnknownFields);
      return this;
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input) {
      return MergeFrom(input, pb::ExtensionRegistry.Empty);
    }
    
    public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
      PrepareBuilder();
      pb::UnknownFieldSet.Builder unknownFields = null;
      uint tag;
      string field_name;
      while (input.ReadTag(out tag, out field_name)) {
        if(tag == 0 && field_name != null) {
          int field_ordinal = global::System.Array.BinarySearch(_returnCreateRoomFieldNames, field_name, global::System.StringComparer.Ordinal);
          if(field_ordinal >= 0)
            tag = _returnCreateRoomFieldTags[field_ordinal];
          else {
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            continue;
          }
        }
        switch (tag) {
          case 0: {
            throw pb::InvalidProtocolBufferException.InvalidTag();
          }
          default: {
            if (pb::WireFormat.IsEndGroupTag(tag)) {
              if (unknownFields != null) {
                this.UnknownFields = unknownFields.Build();
              }
              return this;
            }
            if (unknownFields == null) {
              unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
            }
            ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
            break;
          }
          case 8: {
            result.hasRoomID = input.ReadInt32(ref result.roomID_);
            break;
          }
          case 18: {
            result.hasUserinfo = input.ReadString(ref result.userinfo_);
            break;
          }
        }
      }
      
      if (unknownFields != null) {
        this.UnknownFields = unknownFields.Build();
      }
      return this;
    }
    
    
    public bool HasRoomID {
      get { return result.hasRoomID; }
    }
    public int RoomID {
      get { return result.RoomID; }
      set { SetRoomID(value); }
    }
    public Builder SetRoomID(int value) {
      PrepareBuilder();
      result.hasRoomID = true;
      result.roomID_ = value;
      return this;
    }
    public Builder ClearRoomID() {
      PrepareBuilder();
      result.hasRoomID = false;
      result.roomID_ = 0;
      return this;
    }
    
    public bool HasUserinfo {
      get { return result.hasUserinfo; }
    }
    public string Userinfo {
      get { return result.Userinfo; }
      set { SetUserinfo(value); }
    }
    public Builder SetUserinfo(string value) {
      pb::ThrowHelper.ThrowIfNull(value, "value");
      PrepareBuilder();
      result.hasUserinfo = true;
      result.userinfo_ = value;
      return this;
    }
    public Builder ClearUserinfo() {
      PrepareBuilder();
      result.hasUserinfo = false;
      result.userinfo_ = "";
      return this;
    }
  }
  static returnCreateRoom() {
    object.ReferenceEquals(global::CreateRoom.Descriptor, null);
  }
}

#endregion


#endregion Designer generated code
