//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace list_mj.PublicUserInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="registrationactivitiesModel", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class registrationactivitiesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AddDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal BuybackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private list_mj.PublicUserInfo.registrationactivitiesModel[] ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CouponsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GameUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadImgurlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private list_mj.PublicUserInfo.registrationactivitiesModel Parent1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private list_mj.PublicUserInfo.registrationactivitiesModel Parent2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TodayTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnionIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AddDate {
            get {
                return this.AddDateField;
            }
            set {
                if ((this.AddDateField.Equals(value) != true)) {
                    this.AddDateField = value;
                    this.RaisePropertyChanged("AddDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Buyback {
            get {
                return this.BuybackField;
            }
            set {
                if ((this.BuybackField.Equals(value) != true)) {
                    this.BuybackField = value;
                    this.RaisePropertyChanged("Buyback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public list_mj.PublicUserInfo.registrationactivitiesModel[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Coupons {
            get {
                return this.CouponsField;
            }
            set {
                if ((this.CouponsField.Equals(value) != true)) {
                    this.CouponsField = value;
                    this.RaisePropertyChanged("Coupons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameCurrency {
            get {
                return this.GameCurrencyField;
            }
            set {
                if ((this.GameCurrencyField.Equals(value) != true)) {
                    this.GameCurrencyField = value;
                    this.RaisePropertyChanged("GameCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameNum {
            get {
                return this.GameNumField;
            }
            set {
                if ((this.GameNumField.Equals(value) != true)) {
                    this.GameNumField = value;
                    this.RaisePropertyChanged("GameNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GameUserID {
            get {
                return this.GameUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GameUserIDField, value) != true)) {
                    this.GameUserIDField = value;
                    this.RaisePropertyChanged("GameUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeadImgurl {
            get {
                return this.HeadImgurlField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadImgurlField, value) != true)) {
                    this.HeadImgurlField = value;
                    this.RaisePropertyChanged("HeadImgurl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastTime {
            get {
                return this.LastTimeField;
            }
            set {
                if ((this.LastTimeField.Equals(value) != true)) {
                    this.LastTimeField = value;
                    this.RaisePropertyChanged("LastTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpenID {
            get {
                return this.OpenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OpenIDField, value) != true)) {
                    this.OpenIDField = value;
                    this.RaisePropertyChanged("OpenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public list_mj.PublicUserInfo.registrationactivitiesModel Parent1 {
            get {
                return this.Parent1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parent1Field, value) != true)) {
                    this.Parent1Field = value;
                    this.RaisePropertyChanged("Parent1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public list_mj.PublicUserInfo.registrationactivitiesModel Parent2 {
            get {
                return this.Parent2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parent2Field, value) != true)) {
                    this.Parent2Field = value;
                    this.RaisePropertyChanged("Parent2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentID {
            get {
                return this.ParentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIDField, value) != true)) {
                    this.ParentIDField = value;
                    this.RaisePropertyChanged("ParentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TodayTotal {
            get {
                return this.TodayTotalField;
            }
            set {
                if ((this.TodayTotalField.Equals(value) != true)) {
                    this.TodayTotalField = value;
                    this.RaisePropertyChanged("TodayTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnionID {
            get {
                return this.UnionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UnionIDField, value) != true)) {
                    this.UnionIDField = value;
                    this.RaisePropertyChanged("UnionID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PublicUserInfo.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUserInfo", ReplyAction="http://tempuri.org/IUser/UpdateUserInfoResponse")]
        string UpdateUserInfo(list_mj.PublicUserInfo.registrationactivitiesModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUserInfo", ReplyAction="http://tempuri.org/IUser/UpdateUserInfoResponse")]
        System.Threading.Tasks.Task<string> UpdateUserInfoAsync(list_mj.PublicUserInfo.registrationactivitiesModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateGameCurrency", ReplyAction="http://tempuri.org/IUser/UpdateGameCurrencyResponse")]
        string UpdateGameCurrency(string unionid, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateGameCurrency", ReplyAction="http://tempuri.org/IUser/UpdateGameCurrencyResponse")]
        System.Threading.Tasks.Task<string> UpdateGameCurrencyAsync(string unionid, int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetGameCurrency", ReplyAction="http://tempuri.org/IUser/GetGameCurrencyResponse")]
        string GetGameCurrency(string unionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetGameCurrency", ReplyAction="http://tempuri.org/IUser/GetGameCurrencyResponse")]
        System.Threading.Tasks.Task<string> GetGameCurrencyAsync(string unionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetGameCurrencyList", ReplyAction="http://tempuri.org/IUser/GetGameCurrencyListResponse")]
        string GetGameCurrencyList(string unionid, string COntype, int pageindex, int pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetGameCurrencyList", ReplyAction="http://tempuri.org/IUser/GetGameCurrencyListResponse")]
        System.Threading.Tasks.Task<string> GetGameCurrencyListAsync(string unionid, string COntype, int pageindex, int pagesize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetSubordinateAmountList", ReplyAction="http://tempuri.org/IUser/GetSubordinateAmountListResponse")]
        string GetSubordinateAmountList(string unionid, string Contype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetSubordinateAmountList", ReplyAction="http://tempuri.org/IUser/GetSubordinateAmountListResponse")]
        System.Threading.Tasks.Task<string> GetSubordinateAmountListAsync(string unionid, string Contype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo_Openid", ReplyAction="http://tempuri.org/IUser/GetUserInfo_OpenidResponse")]
        string GetUserInfo_Openid(string openid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo_Openid", ReplyAction="http://tempuri.org/IUser/GetUserInfo_OpenidResponse")]
        System.Threading.Tasks.Task<string> GetUserInfo_OpenidAsync(string openid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo_Unionid", ReplyAction="http://tempuri.org/IUser/GetUserInfo_UnionidResponse")]
        string GetUserInfo_Unionid(string unionid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserInfo_Unionid", ReplyAction="http://tempuri.org/IUser/GetUserInfo_UnionidResponse")]
        System.Threading.Tasks.Task<string> GetUserInfo_UnionidAsync(string unionid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : list_mj.PublicUserInfo.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<list_mj.PublicUserInfo.IUser>, list_mj.PublicUserInfo.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string UpdateUserInfo(list_mj.PublicUserInfo.registrationactivitiesModel model) {
            return base.Channel.UpdateUserInfo(model);
        }
        
        public System.Threading.Tasks.Task<string> UpdateUserInfoAsync(list_mj.PublicUserInfo.registrationactivitiesModel model) {
            return base.Channel.UpdateUserInfoAsync(model);
        }
        
        public string UpdateGameCurrency(string unionid, int num) {
            return base.Channel.UpdateGameCurrency(unionid, num);
        }
        
        public System.Threading.Tasks.Task<string> UpdateGameCurrencyAsync(string unionid, int num) {
            return base.Channel.UpdateGameCurrencyAsync(unionid, num);
        }
        
        public string GetGameCurrency(string unionid) {
            return base.Channel.GetGameCurrency(unionid);
        }
        
        public System.Threading.Tasks.Task<string> GetGameCurrencyAsync(string unionid) {
            return base.Channel.GetGameCurrencyAsync(unionid);
        }
        
        public string GetGameCurrencyList(string unionid, string COntype, int pageindex, int pagesize) {
            return base.Channel.GetGameCurrencyList(unionid, COntype, pageindex, pagesize);
        }
        
        public System.Threading.Tasks.Task<string> GetGameCurrencyListAsync(string unionid, string COntype, int pageindex, int pagesize) {
            return base.Channel.GetGameCurrencyListAsync(unionid, COntype, pageindex, pagesize);
        }
        
        public string GetSubordinateAmountList(string unionid, string Contype) {
            return base.Channel.GetSubordinateAmountList(unionid, Contype);
        }
        
        public System.Threading.Tasks.Task<string> GetSubordinateAmountListAsync(string unionid, string Contype) {
            return base.Channel.GetSubordinateAmountListAsync(unionid, Contype);
        }
        
        public string GetUserInfo_Openid(string openid) {
            return base.Channel.GetUserInfo_Openid(openid);
        }
        
        public System.Threading.Tasks.Task<string> GetUserInfo_OpenidAsync(string openid) {
            return base.Channel.GetUserInfo_OpenidAsync(openid);
        }
        
        public string GetUserInfo_Unionid(string unionid) {
            return base.Channel.GetUserInfo_Unionid(unionid);
        }
        
        public System.Threading.Tasks.Task<string> GetUserInfo_UnionidAsync(string unionid) {
            return base.Channel.GetUserInfo_UnionidAsync(unionid);
        }
    }
}
